using System.Net;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using Elastic.Clients.Elasticsearch;
using Elastic.Transport;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Diagnostics.HealthChecks;

namespace VirtoCommerce.AppHost.Extensions;

public static class ElasticsearchExtensions
{
    public static ElasticsearchResources AddElasticsearchWithKibana(
        this IDistributedApplicationBuilder builder,
        AppHostOptions options)
    {
        var scriptsPath = Path.Combine(builder.AppHostDirectory, "scripts");
        var localCertsPath = Path.Combine(builder.AppHostDirectory, ".certs");
        var elasticCertFingerprint = EnsureElasticCerts(localCertsPath);

        // Elasticsearch container
        var elasticPassword = builder.AddParameter("ElasticPassword", secret: true);
        var elasticsearch = builder.AddContainer("elasticsearch", "elasticsearch", options.ElasticsearchVersion)
            .WithHttpsEndpoint(options.ElasticsearchPort, options.ElasticsearchPort)
            .WithEnvironment("ELASTIC_PASSWORD", elasticPassword)
            .WithEnvironment("discovery.type", "single-node")
            .WithEnvironment("bootstrap.memory_lock", "true")
            .WithEnvironment("ES_JAVA_OPTS", $"-Xms{options.ElasticsearchHeapSize} -Xmx{options.ElasticsearchHeapSize}")
            .WithEnvironment("xpack.security.enabled", "true")
            .WithEnvironment("xpack.license.self_generated.type", options.ElasticsearchLicense)
            .WithEnvironment("xpack.ml.use_auto_machine_memory_percent", "true")
            .WithEnvironment("network.host", "0.0.0.0")
            .WithContainerRuntimeArgs("--ulimit", "memlock=-1:-1")
            .WithContainerRuntimeArgs("--memory", options.ElasticsearchMemoryLimit)
            .WithContainerRuntimeArgs("--memory-swap", options.ElasticsearchMemoryLimit);

        elasticsearch.WithVolume(VolumeNameGenerator.Generate(elasticsearch, "data"), "/usr/share/elasticsearch/data");
        elasticPassword.WithParentRelationship(elasticsearch);

        // Certificate setup
        var certsVolume = VolumeNameGenerator.Generate(elasticsearch, "certs");
        var certSetup = elasticsearch.AddCertificateSetupContainer(localCertsPath, scriptsPath, certsVolume);

        // SSL configuration
        elasticsearch.ConfigureSsl(certSetup, certsVolume);

        // Health check
        elasticsearch.AddElasticsearchHealthCheck(elasticPassword, elasticCertFingerprint);

        // Kibana
        var kibana = elasticsearch.AddKibana(elasticPassword, scriptsPath, certsVolume, options);

        return new ElasticsearchResources
        {
            Elasticsearch = elasticsearch,
            Kibana = kibana,
            ElasticPassword = elasticPassword,
            CertFingerprint = elasticCertFingerprint,
        };
    }

    private static string EnsureElasticCerts(string certsPath, string caName = "ca.crt", string certName = "es.crt", string keyName = "es.key")
    {
        Directory.CreateDirectory(certsPath);

        var caPath = Path.Combine(certsPath, caName);
        var certPath = Path.Combine(certsPath, certName);
        var keyPath = Path.Combine(certsPath, keyName);
        X509Certificate2? caCert = null;

        try
        {
            if (!File.Exists(caPath) || !File.Exists(certPath) || !File.Exists(keyPath))
            {
                // CA
                using var caKey = RSA.Create(2048);
                var caReq = new CertificateRequest("CN=Aspire Autogenerated CA", caKey, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
                caReq.CertificateExtensions.Add(
                    new X509BasicConstraintsExtension(certificateAuthority: true, hasPathLengthConstraint: false, pathLengthConstraint: 0, critical: true));
                caCert = caReq.CreateSelfSigned(DateTimeOffset.Now, DateTimeOffset.Now.AddYears(3));
                File.WriteAllText(caPath, caCert.ExportCertificatePem());

                // ES Cert (Signed by CA)
                using var certKey = RSA.Create(2048);
                var certReq = new CertificateRequest("CN=elasticsearch", certKey, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);

                // SANs (Subject Alternative Names)
                var sanBuilder = new SubjectAlternativeNameBuilder();
                sanBuilder.AddDnsName("elasticsearch");
                sanBuilder.AddDnsName("kibana");
                sanBuilder.AddDnsName("localhost");
                sanBuilder.AddDnsName("host.docker.internal");
                sanBuilder.AddIpAddress(IPAddress.Parse("127.0.0.1"));
                certReq.CertificateExtensions.Add(sanBuilder.Build());

                using var esCert = certReq.Create(caCert, DateTimeOffset.Now, DateTimeOffset.Now.AddYears(3), Guid.NewGuid().ToByteArray());

                File.WriteAllText(certPath, esCert.ExportCertificatePem());
                File.WriteAllText(keyPath, certKey.ExportPkcs8PrivateKeyPem()); // Unencrypted key for Docker
            }
            else
            {
                // Load existing CA cert
                caCert = new X509Certificate2(caPath);
            }

            // Elastic expects the HEX string of the CA's SHA256 hash
            var fingerprint = caCert.GetCertHashString(HashAlgorithmName.SHA256);

            return fingerprint;
        }
        finally
        {
            caCert?.Dispose();
        }
    }

    private static IResourceBuilder<ContainerResource> AddCertificateSetupContainer(
        this IResourceBuilder<ContainerResource> elasticsearch,
        string localCertsPath,
        string scriptsPath,
        string certsVolume)
    {
        return elasticsearch.ApplicationBuilder.AddContainer("elasticsearch-certs-setup", "alpine/curl")
            .WithBindMount(localCertsPath, "/source", isReadOnly: true)
            .WithVolume(certsVolume, "/dest")
            .WithBindMount(scriptsPath, "/scripts", isReadOnly: true)
            .WithEntrypoint("/bin/sh")
            .WithArgs("/scripts/elasticsearch-certs-setup.sh")
            .WithLifetime(ContainerLifetime.Session);
    }

    private static void ConfigureSsl(
        this IResourceBuilder<ContainerResource> elasticsearch,
        IResourceBuilder<ContainerResource> certSetup,
        string certsVolume)
    {
        elasticsearch
            .WithEnvironment("xpack.security.http.ssl.enabled", "true")
            .WithEnvironment("xpack.security.http.ssl.key", "certs/es.key")
            .WithEnvironment("xpack.security.http.ssl.certificate", "certs/es.crt")
            .WithEnvironment("xpack.security.http.ssl.certificate_authorities", "certs/ca.crt")
            .WithEnvironment("xpack.security.transport.ssl.enabled", "true")
            .WithEnvironment("xpack.security.transport.ssl.key", "certs/es.key")
            .WithEnvironment("xpack.security.transport.ssl.certificate", "certs/es.crt")
            .WithEnvironment("xpack.security.transport.ssl.certificate_authorities", "certs/ca.crt")
            .WithEnvironment("xpack.security.transport.ssl.verification_mode", "certificate")
            .WithVolume(certsVolume, "/usr/share/elasticsearch/config/certs")
            .WaitForCompletion(certSetup);
    }

    private static void AddElasticsearchHealthCheck(
        this IResourceBuilder<ContainerResource> elasticsearch,
        IResourceBuilder<ParameterResource> elasticPassword,
        string certFingerprint)
    {
        var healthCheckName = $"{elasticsearch.Resource.Name}_check";
        var clientLock = new object();
        ElasticsearchClient? client = null;

        elasticsearch.ApplicationBuilder.Services.AddHealthChecks()
            .AddAsyncCheck(healthCheckName, async ct =>
            {
                if (client is null)
                {
                    try
                    {
                        var url = elasticsearch.GetEndpoint("https").Url;
                        var password = await elasticPassword.Resource.GetValueAsync(ct);

                        if (!string.IsNullOrEmpty(url) && !string.IsNullOrEmpty(password))
                        {
                            lock (clientLock)
                            {
                                client ??= new ElasticsearchClient(
                                    new ElasticsearchClientSettings(new Uri(url))
                                        .Authentication(new BasicAuthentication("elastic", password))
                                        .CertificateFingerprint(certFingerprint));
                            }
                        }
                    }
                    catch
                    {
                        return HealthCheckResult.Unhealthy("Waiting for connection details...");
                    }
                }

                if (client is null)
                {
                    return HealthCheckResult.Unhealthy("Elasticsearch client is not initialized.");
                }

                try
                {
                    var pingResponse = await client.PingAsync(ct).ConfigureAwait(false);

                    return pingResponse.IsValidResponse
                        ? HealthCheckResult.Healthy()
                        : HealthCheckResult.Unhealthy(pingResponse.DebugInformation, pingResponse.ApiCallDetails.OriginalException);
                }
                catch (Exception ex)
                {
                    return HealthCheckResult.Unhealthy(exception: ex);
                }
            });

        elasticsearch.WithHealthCheck(healthCheckName);
    }

    private static IResourceBuilder<ContainerResource> AddKibana(
        this IResourceBuilder<ContainerResource> elasticsearch,
        IResourceBuilder<ParameterResource> elasticPassword,
        string scriptsPath,
        string certsVolume,
        AppHostOptions options)
    {
        var builder = elasticsearch.ApplicationBuilder;
        var kibanaPassword = builder.AddParameter("KibanaPassword", secret: true);

        // Kibana user setup container
        builder.AddContainer("kibana-user-setup", "alpine/curl")
            .WithEnvironment("ELASTIC_USER", "elastic")
            .WithEnvironment("ELASTIC_PASSWORD", elasticPassword)
            .WithEnvironment("KIBANA_USER", "kibana_system")
            .WithEnvironment("KIBANA_PASSWORD", kibanaPassword)
            .WithEnvironment("ELASTIC_HOST", "https://elasticsearch:9200")
            .WithVolume(certsVolume, "/certs")
            .WithBindMount(scriptsPath, "/scripts", isReadOnly: true)
            .WithEntrypoint("/bin/sh")
            .WithArgs("/scripts/kibana-user-setup.sh")
            .WaitFor(elasticsearch);

        var kibanaEncryptionKey = builder.AddParameter("KibanaEncryptionKey", secret: true);
        var kibana = builder.AddContainer("kibana", "kibana", options.ElasticsearchVersion)
            .WithHttpsEndpoint(options.KibanaPort, options.KibanaPort)
            .WithEnvironment("SERVERNAME", "kibana")
            .WithEnvironment("ELASTICSEARCH_HOSTS", "https://elasticsearch:9200")
            .WithEnvironment("ELASTICSEARCH_USERNAME", "kibana_system")
            .WithEnvironment("ELASTICSEARCH_PASSWORD", kibanaPassword)
            .WithEnvironment("ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES", "config/certs/ca.crt")
            .WithEnvironment("ELASTICSEARCH_SSL_VERIFICATIONMODE", "certificate")
            .WithEnvironment("SERVER_SSL_ENABLED", "true")
            .WithEnvironment("SERVER_SSL_CERTIFICATE", "config/certs/es.crt")
            .WithEnvironment("SERVER_SSL_KEY", "config/certs/es.key")
            .WithEnvironment("XPACK_SECURITY_SECURECOOKIES", "true")
            .WithEnvironment("XPACK_SECURITY_ENCRYPTIONKEY", kibanaEncryptionKey)
            .WithEnvironment("XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY", kibanaEncryptionKey)
            .WithEnvironment("XPACK_REPORTING_ENCRYPTIONKEY", kibanaEncryptionKey)
            .WithVolume(certsVolume, "/usr/share/kibana/config/certs")
            .WithRelationship(elasticsearch.Resource, "kibana")
            .WaitFor(elasticsearch);

        kibana.WithVolume(VolumeNameGenerator.Generate(kibana, "data"), "/usr/share/kibana/data");
        kibanaPassword.WithParentRelationship(kibana);
        kibanaEncryptionKey.WithParentRelationship(kibana);

        return kibana;
    }
}

public record ElasticsearchResources
{
    public required IResourceBuilder<ContainerResource> Elasticsearch { get; init; }

    public required IResourceBuilder<ContainerResource> Kibana { get; init; }

    public required IResourceBuilder<ParameterResource> ElasticPassword { get; init; }

    public required string CertFingerprint { get; init; }
}
